// Generated by Karakum - do not modify it manually!



package createserver



sealed external interface HandleFunction {
    interface SimpleHandleFunction: HandleFunction
    interface NextHandleFunction: HandleFunction
    interface ErrorHandleFunction: HandleFunction
}
